#! /bin/sh

wal -n &
polybar &
picom -b &
fcitx5 -d &
nitrogen --restore &
sxhkd -c ${HOME}/.config/sxhkd/sxhkdrc &

. "${HOME}/.cache/wal/colors.sh" &

bspc config focused_border_color "$background"
bspc config normal_border_color  "$background"
bspc config active_border_color  "$background"
bspc config presel_feedback_color "$color2"

bspc monitor -d F L O W E R

bspc config border_width	2
bspc config window_gap		2 
bspc config split_ratio		0.50

config borderless_monocle true
config focus_follows_pointer true
config gapless_monocle true
